name: CAC2020
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  tflite: ^1.1.1
  path_provider: ^1.6.11
  image_picker: ^0.6.7+4
  camera:
  image: ^2.1.14
  firebase_auth: ^0.14.0+5
  firebase_storage: ^3.1.6
  cloud_firestore: ^0.12.9+5
  google_sign_in: ^4.4.4
  provider: ^4.1.3
  ml_linalg: ^12.17.1
  circular_countdown: ^1.2.1
  geolocator: ^6.0.0+4
  google_maps_flutter: ^0.5.33
  permission_handler: ^5.0.1+1
  material_floating_search_bar: ^0.1.7
  flappy_search_bar: ^1.7.2
  toggle_switch: "^0.1.8"
  video_player: ^0.11.0
  sleek_circular_slider: ^1.1.0
  confetti: ^0.5.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/background.jpg
    - assets/posenet_mv1_075_float_from_checkpoints.tflite
    - assets/images/tileImage.jpg
    - assets/images/planetfit.jpeg
    - assets/images/fit1.png
    - assets/images/fit2.png
    - assets/images/temp.mp4
    - assets/images/win.png
    - assets/images/jumpingjacks.mp4
    - assets/images/person1.png
    - assets/images/person2.png
    - assets/images/person3.png
    - assets/images/person4.png
    - assets/images/person5.png
    - assets/images/firstThumbnail.jpeg
    - assets/images/mainThumbnail.jpeg


    #CAC2020/assets/images/tileImage.jpg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
